spring.application.name=ttb-api

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
## logging
logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type.descriptor.sql.spi=trace
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.config.activate.on-profile=testdb
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MYSQL
spring.jpa.database=h2
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.defer-datasource-initialization=true
spring.datasource.username=sa
spring.datasource.password=1

# API prefix 설정
server.servlet.context-path=/api