spring.application.name=ttb-api

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
## logging
logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type.descriptor.sql.spi=trace
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=mysql

spring.datasource.url=ENC(cGB6iIvCIPyBrNJEl/h82Mzh5Q63jJdQiXHV+sgSdpOcM5wRTO89zBpNgcw6xPUv)
spring.datasource.username=ENC(87ebmLP6LZsKzbZCm7K8XA==)
spring.datasource.password=ENC(UFJ/E1PxBKj85ImWNWp+jl59HUhF5E4K)
spring.jpa.properties.hibernate.default_schema=ENC(0KSyMBfltVuBfeuUrgOTEg==)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=false

# API prefix 설정
server.servlet.context-path=/api